// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package schema

import (
	"time"
)

// Defines values for PFSkillSearchModelsCareerRole.
const (
	Business PFSkillSearchModelsCareerRole = "Business"
	Engineer PFSkillSearchModelsCareerRole = "Engineer"
	Manager  PFSkillSearchModelsCareerRole = "Manager"
	Other    PFSkillSearchModelsCareerRole = "Other"
)

// HealthResponse Base model for all API responses
type HealthResponse = PFSkillSearchBaseResponse

// PFSkillSearchBaseResponse Base model for all API responses
type PFSkillSearchBaseResponse struct {
	// Message Response message
	Message *string `json:"message,omitempty"`

	// Success Whether the request was successful
	Success bool `json:"success"`

	// Timestamp Response timestamp
	Timestamp time.Time `json:"timestamp"`
}

// PFSkillSearchModelsCareer defines model for PFSkillSearch.Models.Career.
type PFSkillSearchModelsCareer struct {
	Company     string                        `json:"company"`
	Description *string                       `json:"description,omitempty"`
	EndMonth    *int16                        `json:"end_month,omitempty"`
	Position    string                        `json:"position"`
	Role        PFSkillSearchModelsCareerRole `json:"role"`
	StartMonth  int16                         `json:"start_month"`
}

// PFSkillSearchModelsCareerRole defines model for PFSkillSearchModelsCareer.Role.
type PFSkillSearchModelsCareerRole string

// PFSkillSearchModelsHalfReview defines model for PFSkillSearch.Models.HalfReview.
type PFSkillSearchModelsHalfReview struct {
	CycleStartDate                      string `json:"cycle_start_date"`
	EmployeeId                          string `json:"employee_id"`
	EmploymentType                      string `json:"employment_type"`
	FyCycle                             string `json:"fy_cycle"`
	HalfYearSelfReviewAchievementGrowth string `json:"half_year_self_review_achievement_growth"`
	JobFamily                           string `json:"job_family"`
	MedTerm23yr                         string `json:"med_term_2_3yr"`
	Org1                                string `json:"org1"`
	Org2                                string `json:"org2"`
	RowNum                              string `json:"row_num"`
	SelfAssessmentScore                 string `json:"self_assessment_score"`
	ShortTerm1yr                        string `json:"short_term_1yr"`
	UploadYearMonth                     string `json:"upload_year_month"`
}

// PFSkillSearchModelsMonthlyReview defines model for PFSkillSearch.Models.MonthlyReview.
type PFSkillSearchModelsMonthlyReview struct {
	CycleStartDate string  `json:"cycle_start_date"`
	EmployeeId     string  `json:"employee_id"`
	EmploymentType string  `json:"employment_type"`
	FyCycle        string  `json:"fy_cycle"`
	JobFamily      string  `json:"job_family"`
	MonthlyGoal    string  `json:"monthly_goal"`
	MonthlyReview  string  `json:"monthly_review"`
	Org1           string  `json:"org1"`
	Org2           string  `json:"org2"`
	Org3           *string `json:"org3,omitempty"`
	YearMonth      string  `json:"year_month"`
}

// PFSkillSearchModelsPayloadFindPersonRequest defines model for PFSkillSearch.Models.Payload.FindPersonRequest.
type PFSkillSearchModelsPayloadFindPersonRequest struct {
	Instructions string                     `json:"instructions"`
	Person       *PFSkillSearchModelsPerson `json:"person,omitempty"`
	Persona      PFSkillSearchModelsPersona `json:"persona"`
}

// PFSkillSearchModelsPayloadFindPersonResponse defines model for PFSkillSearch.Models.Payload.FindPersonResponse.
type PFSkillSearchModelsPayloadFindPersonResponse struct {
	// Result The status of the search operation
	Result []PFSkillSearchModelsPayloadFindPersonResult `json:"result"`
}

// PFSkillSearchModelsPayloadFindPersonResult defines model for PFSkillSearch.Models.Payload.FindPersonResult.
type PFSkillSearchModelsPayloadFindPersonResult struct {
	// Description Optional description of the match
	Description *string `json:"description,omitempty"`

	// Person The person object that was matched
	Person PFSkillSearchModelsPerson `json:"person"`

	// Score Similarity score between 0.0 and 1.0
	Score float32 `json:"score"`
}

// PFSkillSearchModelsPayloadSearchPeopleResponse defines model for PFSkillSearch.Models.Payload.SearchPeopleResponse.
type PFSkillSearchModelsPayloadSearchPeopleResponse struct {
	// Description Optional description of the match
	Description *string `json:"description,omitempty"`

	// Person The person object that was matched
	Person PFSkillSearchModelsPerson `json:"person"`

	// Score Similarity score between 0.0 and 1.0
	Score float32 `json:"score"`
}

// PFSkillSearchModelsPerson defines model for PFSkillSearch.Models.Person.
type PFSkillSearchModelsPerson struct {
	Age                            string  `json:"age"`
	Birthday                       string  `json:"birthday"`
	CurrentEmployeeFlag            string  `json:"current_employee_flag"`
	Dept1                          string  `json:"dept_1"`
	Dept2                          string  `json:"dept_2"`
	Dept3                          *string `json:"dept_3,omitempty"`
	Dept4                          *string `json:"dept_4,omitempty"`
	Dept5                          *string `json:"dept_5,omitempty"`
	Dept6                          *string `json:"dept_6,omitempty"`
	EmployeeId                     string  `json:"employee_id"`
	EmployeeName                   string  `json:"employee_name"`
	EmploymentCategory             *string `json:"employment_category,omitempty"`
	EmploymentType                 string  `json:"employment_type"`
	EnteredAt                      string  `json:"entered_at"`
	FulltimeEmployeeHiredAt        *string `json:"fulltime_employee_hired_at,omitempty"`
	FulltimeEmployeeRetiredAt      *string `json:"fulltime_employee_retired_at,omitempty"`
	Gender                         string  `json:"gender"`
	GradeCombined                  *string `json:"grade_combined,omitempty"`
	JobFamily                      string  `json:"job_family"`
	JobTitle                       string  `json:"job_title"`
	JpNonJpClassification          string  `json:"jp_non_jp_classification"`
	LastDayAt                      *string `json:"last_day_at,omitempty"`
	LatestJobGrade                 *string `json:"latest_job_grade,omitempty"`
	LatestOrgGrade                 *string `json:"latest_org_grade,omitempty"`
	LoadDate                       string  `json:"load_date"`
	Location                       string  `json:"location"`
	Mail                           string  `json:"mail"`
	Nickname                       *string `json:"nickname,omitempty"`
	RecruitmentCategoryNewGraduate string  `json:"recruitment_category_new_graduate"`
	RetiredAt                      *string `json:"retired_at,omitempty"`
	SalaryTable                    string  `json:"salary_table"`
	YearsOfService                 string  `json:"years_of_service"`
}

// PFSkillSearchModelsPersona defines model for PFSkillSearch.Models.Persona.
type PFSkillSearchModelsPersona struct {
	Career []PFSkillSearchModelsCareer `json:"career"`
	Name   string                      `json:"name"`
	Skills []PFSkillSearchModelsSkill  `json:"skills"`
}

// PFSkillSearchModelsSkill defines model for PFSkillSearch.Models.Skill.
type PFSkillSearchModelsSkill struct {
	// Description Optional description of the skill
	Description *string `json:"description,omitempty"`

	// Experience Skill experience in years
	Experience int16 `json:"experience"`

	// Name Skill name
	Name string `json:"name"`
}

// GetPersonByIdJSONBody defines parameters for GetPersonById.
type GetPersonByIdJSONBody struct {
	Id string `json:"id"`
}

// GetPersonByIdJSONRequestBody defines body for GetPersonById for application/json ContentType.
type GetPersonByIdJSONRequestBody GetPersonByIdJSONBody

// FindPersonJSONRequestBody defines body for FindPerson for application/json ContentType.
type FindPersonJSONRequestBody = PFSkillSearchModelsPayloadFindPersonRequest

// GeneratePersonaJSONRequestBody defines body for GeneratePersona for application/json ContentType.
type GeneratePersonaJSONRequestBody = PFSkillSearchModelsPerson
