// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package schema

import (
	"time"
)

// HealthResponse Base model for all API responses
type HealthResponse = PFSkillSearchBaseResponse

// PFSkillSearchBaseResponse Base model for all API responses
type PFSkillSearchBaseResponse struct {
	// Message Response message
	Message *string `json:"message,omitempty"`

	// Success Whether the request was successful
	Success bool `json:"success"`

	// Timestamp Response timestamp
	Timestamp time.Time `json:"timestamp"`
}

// PFSkillSearchModelsPerson defines model for PFSkillSearch.Models.Person.
type PFSkillSearchModelsPerson struct {
	Age                            string  `json:"age"`
	Birthday                       string  `json:"birthday"`
	CurrentEmployeeFlag            string  `json:"current_employee_flag"`
	Dept1                          string  `json:"dept_1"`
	Dept2                          string  `json:"dept_2"`
	Dept3                          *string `json:"dept_3,omitempty"`
	Dept4                          *string `json:"dept_4,omitempty"`
	Dept5                          *string `json:"dept_5,omitempty"`
	Dept6                          *string `json:"dept_6,omitempty"`
	EmployeeId                     string  `json:"employee_id"`
	EmployeeName                   string  `json:"employee_name"`
	EmploymentCategory             *string `json:"employment_category,omitempty"`
	EmploymentType                 string  `json:"employment_type"`
	EnteredAt                      string  `json:"entered_at"`
	FulltimeEmployeeHiredAt        *string `json:"fulltime_employee_hired_at,omitempty"`
	FulltimeEmployeeRetiredAt      *string `json:"fulltime_employee_retired_at,omitempty"`
	Gender                         string  `json:"gender"`
	GradeCombined                  *string `json:"grade_combined,omitempty"`
	JobFamily                      string  `json:"job_family"`
	JobTitle                       string  `json:"job_title"`
	JpNonJpClassification          string  `json:"jp_non_jp_classification"`
	LastDayAt                      *string `json:"last_day_at,omitempty"`
	LatestJobGrade                 *string `json:"latest_job_grade,omitempty"`
	LatestOrgGrade                 *string `json:"latest_org_grade,omitempty"`
	LoadDate                       string  `json:"load_date"`
	Location                       string  `json:"location"`
	Mail                           string  `json:"mail"`
	Nickname                       *string `json:"nickname,omitempty"`
	RecruitmentCategoryNewGraduate string  `json:"recruitment_category_new_graduate"`
	RetiredAt                      *string `json:"retired_at,omitempty"`
	SalaryTable                    string  `json:"salary_table"`
	YearsOfService                 string  `json:"years_of_service"`
}

// GetPersonByIdJSONBody defines parameters for GetPersonById.
type GetPersonByIdJSONBody struct {
	Id string `json:"id"`
}

// GetPersonByIdJSONRequestBody defines body for GetPersonById for application/json ContentType.
type GetPersonByIdJSONRequestBody GetPersonByIdJSONBody
